@WeatherApi_HostAddress = http://localhost:5270

GET {{WeatherApi_HostAddress}}/health
Accept: application/json

###

GET {{WeatherApi_HostAddress}}/api/locations?query=Córdoba&limit=5
Accept: application/json

###

GET {{WeatherApi_HostAddress}}/api/weather?latitude=-31.4167&longitude=-64.1833
Accept: application/json

###
